# Docker Compose for AutoChef - Local Development
# This orchestrates both services for easy local testing

services:
  # Python FastAPI Service (LLM Backend)
  python-service:
    build: 
      context: ./autochefpythonservice
      dockerfile: Dockerfile
    container_name: autochef-python-local
    ports:
      - "5001:5001"
    environment:
      # AWS credentials passed from host environment
      - AWS_REGION=us-east-1
      # These will use your local AWS credentials
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  # Java Spring Boot Service (API Gateway)
  java-service:
    build:
      context: ./autochefjavaservice
      dockerfile: Dockerfile
    container_name: autochef-java-local
    ports:
      - "8080:8080"
    environment:
      # Override the LLM service URL to use container name
      # Use Spring Boot standard environment variable format  
      - LLM_SERVICE_URL=http://python-service:5001/api/v1/generate-recipe
    depends_on:
      - python-service

# Optional: Create a custom network (Docker creates one by default)
networks:
  autochef-network:
    driver: bridge